{{- if .Values.devtools.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: devtools
  labels:
    {{- include "dinsro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.devtools.service.type }}
  ports:
  - port: {{ .Values.devtools.service.port }}
    targetPort: devtools
    protocol: TCP
    name: devtools
  selector:
    {{- include "dinsro.devtoolsSelectorLabels" . | nindent 4 }}
{{- end }}
